### PR TITLE
Local Account Token Filter Policy

### PR DESCRIPTION
**Pull request by dtcjoe**

### CODE REVIEW

**Comment by nettts** [comment]
@dtcjoe  can you add details to your pull request? Why do you want this added? What does LocalAccountTokenFilterPolicy do?

**Comment by dtcjoe** [comment]
I have added a script to msft-windows that creates a dword 32 registry entry at  HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System name LocalAccountTokenFilterPolicy with a value of 1. This disables UAC remote restrictions which often causes issues when attempting to perform backups.

**Comment by nettts** [comment]
> I have added a script to msft-windows that creates a dword 32 registry entry at HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System name LocalAccountTokenFilterPolicy with a value of 1. This disables UAC remote restrictions which often causes issues when attempting to perform backups.

Are the backups your performing outside of a domain environment because this change can pose a security risk to the environment. Can you include how your organization is compensating by enabling this?

**Comment by B-Moriik** [comment]
To add to Joe, the backups in question are being performed on Hyper-V hosts which are outside of the domain environment. This is done for security where the security isn't enforced by Policy. The passwords on the Hyper-V hosts are randomly generated. In the future there are plans to rotate them with LAPS. 

We're using Veeam to its full potential.

**Comment by nettts** [comment]
> To add to Joe, the backups in question are being performed on Hyper-V hosts which are outside of the domain environment. This is done for security where the security isn't enforced by Policy. The passwords on the Hyper-V hosts are randomly generated. In the future there are plans to rotate them with LAPS.
> 
> We're using Veeam to its full potential.

Perfect. Approving and merging request.

**Pull request merged**
